<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB; // Add this line to import the DB facade

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Define the users to seed
        $users = [
            [
                'type' => 'administrateur',
                'projet' => 'ADMINISTRATION',
                'id' => 6,
                'email' => 'amranihassan.am@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => 'NyXN9RmPWe1U25MCdammKH8N35b5MYvi3dUAKzYgjT4Tmhae593PbTl1heVv',
                'created_at' => null,
                'updated_at' => '2024-12-30 22:35:26',
                'matricule' => '104',
                'nom' => 'AMRANI',
                'prénom' => 'Hassan',
                'fonction' => 'Developpeur',
                'service' => 'INFORMATIQUE',
                'solde_conge' => 0,
                'responsable_hiarchique' => '952',
                'directeur' => '2',
                'profile_picture' => '104_AMRANI_img.jpg',
                'shift_id' => null,
                'date_entrée' => null,
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'directeur',
                'projet' => 'ACIERIE',
                'id' => 2335,
                'email' => 'a.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-06-29 12:21:33',
                'updated_at' => '2024-09-04 09:57:52',
                'matricule' => '835',
                'nom' => 'EL MOUMNI',
                'prénom' => 'ABDELILAH',
                'fonction' => 'Dirécteur industriel',
                'service' => 'PRODUCTION',
                'solde_conge' => 0,
                'responsable_hiarchique' => '991',
                'directeur' => '835',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => null,
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'directeur',
                'projet' => 'ADMINISTRATION',
                'id' => 2355,
                'email' => 'khalid.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-06-29 12:21:33',
                'updated_at' => '2024-09-04 09:57:52',
                'matricule' => '2',
                'nom' => 'MACHRAH',
                'prénom' => 'KHALID',
                'fonction' => 'Directeur général',
                'service' => 'DIRECTION',
                'solde_conge' => 0,
                'responsable_hiarchique' => null,
                'directeur' => '2',
                'profile_picture' => '2_MACHRAH_img.jpg',
                'shift_id' => null,
                'date_entrée' => null,
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'directeur',
                'projet' => 'LAMINOIR',
                'id' => 2268,
                'email' => 'j.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-06-29 12:21:33',
                'updated_at' => '2024-09-04 09:57:52',
                'matricule' => '914',
                'nom' => 'OUTAISS',
                'prénom' => 'JAMAA',
                'fonction' => 'Directeur laminoir',
                'service' => 'PRODUCTION',
                'solde_conge' => 0,
                'responsable_hiarchique' => null,
                'directeur' => '914',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => null,
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'ouvrier',
                'projet' => 'ACIERIE',
                'id' => 5251,
                'email' => 'y.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-12-07 23:28:03',
                'updated_at' => '2024-12-10 19:01:24',
                'matricule' => 'TNS 2',
                'nom' => 'ZERAI ',
                'prénom' => 'ZOUHAIR ',
                'fonction' => 'Technicien USA',
                'service' => 'UTILITES',
                'solde_conge' => 0,
                'responsable_hiarchique' => '993',
                'directeur' => '835',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => '2024-05-01',
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'ouvrier',
                'projet' => 'ADMINISTRATION',
                'id' => 5236,
                'email' => 'youssef.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-12-07 23:28:03',
                'updated_at' => '2024-12-30 22:34:54',
                'matricule' => 'TNS3',
                'nom' => 'SOUISSI ',
                'prénom' => 'ZAKARIA',
                'fonction' => 'Secretaire  commercial',
                'service' => 'VENTES',
                'solde_conge' => 0,
                'responsable_hiarchique' => '952',
                'directeur' => '2',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => '2024-04-01',
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'ouvrier',
                'projet' => 'CHAUFFEUR',
                'id' => 5165,
                'email' => null,
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-12-07 23:28:03',
                'updated_at' => '2024-09-04 09:57:54',
                'matricule' => 'RT49843',
                'nom' => 'ZIANI',
                'prénom' => 'YASSINE ',
                'fonction' => 'Chauffeur RMO',
                'service' => 'LOGISTIQUE',
                'solde_conge' => 0,
                'responsable_hiarchique' => null,
                'directeur' => '2',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => '2024-01-09',
                'affectation' => 'RMO',
                'equipe_id' => null,
            ],
            [
                'type' => 'ouvrier',
                'projet' => 'LAMINOIR',
                'id' => 5247,
                'email' => 'souad.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-12-07 23:28:03',
                'updated_at' => '2024-09-04 09:57:54',
                'matricule' => 'RT9996',
                'nom' => 'ZOURIRA',
                'prénom' => 'ZOUBIER',
                'fonction' => 'Tuyauteur',
                'service' => 'UTILITES',
                'solde_conge' => 0,
                'responsable_hiarchique' => '989',
                'directeur' => '914',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => '2024-06-27',
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'responsable',
                'projet' => 'ACIERIE',
                'id' => 2320,
                'email' => 'najib.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-06-29 12:21:33',
                'updated_at' => '2024-12-30 22:49:57',
                'matricule' => '993',
                'nom' => 'MEHDAOUI ',
                'prénom' => 'WALID ',
                'fonction' => 'Responsable unite d oxy',
                'service' => 'UTILITES',
                'solde_conge' => 0,
                'responsable_hiarchique' => '993',
                'directeur' => '835',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => '2022-10-11',
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'responsable',
                'projet' => 'ADMINISTRATION',
                'id' => 5166,
                'email' => 'rachid.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => 'cpSjcbml3eqRjQvfqSeteqY7bnq1gM6q4eX5LusRRpo3vOs9VUAiqbvXF5Hh',
                'created_at' => '2024-12-07 23:28:03',
                'updated_at' => '2024-12-30 22:34:54',
                'matricule' => '952',
                'nom' => 'QARQACH',
                'prénom' => 'RACHID',
                'fonction' => 'Résponsable service comptablité',
                'service' => 'VENTES',
                'solde_conge' => 0,
                'responsable_hiarchique' => '952',
                'directeur' => '2',
                'profile_picture' => '952_AMINE_img.jpg',
                'shift_id' => null,
                'date_entrée' => null,
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'responsable',
                'projet' => 'LAMINOIR',
                'id' => 2368,
                'email' => 'rachid.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => 'rYTE80ebNCS9rbzKRgLz7S7M48BtEs9ygFyoexJVUCxnbtaMsU5AGbv85M4L',
                'created_at' => '2024-06-29 12:21:33',
                'updated_at' => '2024-09-05 04:56:03',
                'matricule' => '989',
                'nom' => 'ZOUHAIR',
                'prénom' => 'TARIK',
                'fonction' => 'Resposable Laminage',
                'service' => 'USINAGE',
                'solde_conge' => 0,
                'responsable_hiarchique' => '989',
                'directeur' => '914',
                'profile_picture' => null,
                'shift_id' => null,
                'date_entrée' => null,
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
            [
                'type' => 'rh',
                'projet' => 'ADMINISTRATION',
                'id' => 2366,
                'email' => 'tarik.test@somasteel.ma',
                'email_verified_at' => null,
                'password' => Hash::make('password'), // Hashed password
                'remember_token' => null,
                'created_at' => '2024-06-29 12:21:33',
                'updated_at' => '2024-09-04 09:57:53',
                'matricule' => '668',
                'nom' => 'SEMMAMI',
                'prénom' => 'TARIK',
                'fonction' => 'Responsable RH',
                'service' => 'RH',
                'solde_conge' => 0,
                'responsable_hiarchique' => '668',
                'directeur' => '2',
                'profile_picture' => '668_SEMMAMI_img.jpg',
                'shift_id' => null,
                'date_entrée' => null,
                'affectation' => 'SOMASTEEL',
                'equipe_id' => null,
            ],
        ];

        // Insert the users into the database
        DB::table('users')->insert($users);

        $this->command->info('Users seeded successfully!');
    }
}
